# ?? NOTE: This docker-compose is NOT used for production deployment
# Production uses GitHub Actions with separate Docker containers
# This file is only for local full-stack testing (app + database together)
version: '3.8'

services:
  nginx:
      image: nginx:alpine
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/letsencrypt:/etc/letsencrypt:ro # Tambahkan baris ini
      depends_on:
        - steam-portfolio
      restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: steam-portfolio-db
    environment:
      POSTGRES_DB: steam_portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BizBinchi1@
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d:ro # Added :ro for Read-Only safety
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  steam-portfolio:
    image: ghcr.io/limlyang121/my-portfolio:main
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=steam_portfolio;Username=postgres;Password=BizBinchi1@
    restart: unless-stopped
    container_name: steam-portfolio
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

