services:

  postgres-init:
    user: root
    image: ghcr.io/limlyang121/my-portfolio:main
    volumes:
      - db_init:/docker-entrypoint-initdb.d
    command: cp -r /app/Database/. /docker-entrypoint-initdb.d/
    restart: "no"
  nginx:
      image: nginx:alpine
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/letsencrypt:/etc/letsencrypt:ro
      depends_on:
        - steam-portfolio
      restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: steam-portfolio-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - db_init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    depends_on:
      postgres-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  steam-portfolio:
    image: ghcr.io/limlyang121/my-portfolio:main
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
    restart: unless-stopped
    container_name: steam-portfolio
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  db_init:
